name: 'Rebase'

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:


jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: master
          merge_method: rebase
