name: 'Rebase'

on:
  push:
  schedule:
    - cron: '* * * * *'


jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Rebase
      run: |
          git config user.name ${GITHUB_ACTOR}
          git config user.email ${GITHUB_ACTOR}@example.com
          git remote add upstream https://github.com/kovetskiy/repo1
          git pull --rebase upstream master
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        force: true
