name: 'Rebase'

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:


jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shitiomatic/forkbacon@master
      with:
        upstream_url: "https://github.com/neoclide/coc.nvim" # Required! Upstream https clone URL
        upstream_branch: "master"   # Upstream Branch to use
        branch: "master"
        method: "rebase"
        args: "--no-push"
