name: 'Rebase'

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:


jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shitiomatic/forkbacon@master
      with:
        upstream_url: "https://github.com/kovetskiy/repo1"
        upstream_branch: "master"
        branch: "master"
        method: "rebase"
